version: '3.8'

services:
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: kimviiii/gramaconnect-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/gramaconnect
    volumes:
      - ./back-end:/app
    depends_on:
      - mongodb
    restart: always
    
  mongodb:
    image: mongo:4.4
    container_name: gramaconnect_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database_dump:/database_dump

volumes:
  mongodb_data: